description: To get agent workspace deployment runtime logs, send a GET request to
  `/v2/gen-ai/agent-workspaces/{agent_workspace_name}/agent-deployments/{agent_deployment_name}/logs`.
operationId: genai_get_agent_workspace_deployment_runtime_logs
parameters:
- description: Unique agent workspace name
  example: '"example string"'
  in: path
  name: agent_workspace_name
  required: true
  schema:
    type: string
- description: The name of the deployment
  example: '"example string"'
  in: path
  name: agent_deployment_name
  required: true
  schema:
    type: string
- description: Whether to follow live logs.
  example: true
  in: query
  name: follow
  schema:
    type: boolean
- description: Number of log lines to fetch.
  example: '"example string"'
  in: query
  name: tail_lines
  schema:
    type: string
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: ./definitions.yml#/apiGetAgentWorkspaceDeploymentRuntimeLogsOutput
    description: A successful response.
    headers:
      ratelimit-limit:
        $ref: ../../shared/headers.yml#/ratelimit-limit
      ratelimit-remaining:
        $ref: ../../shared/headers.yml#/ratelimit-remaining
      ratelimit-reset:
        $ref: ../../shared/headers.yml#/ratelimit-reset
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "404":
    $ref: ../../shared/responses/not_found.yml
  "429":
    $ref: ../../shared/responses/too_many_requests.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
security:
- bearer_auth:
  - genai:read
summary: Get Agent Workspace Deployment Runtime Logs
tags:
- GradientAI Platform
x-codeSamples:
- $ref: examples/curl/genai_get_agent_workspace_deployment_runtime_logs.yml
