description: To create a new agent workspace deployment release, send a POST request
  to `/v2/gen-ai/agent-workspaces/{agent_workspace_name}/agent-deployments/{agent_deployment_name}/releases`.
  The response body contains a JSON object with the newly created agent workspace
  deployment release object.
operationId: genai_create_agent_workspace_deployment_release
parameters:
- description: The name of agent workspace
  example: '"example string"'
  in: path
  name: agent_workspace_name
  required: true
  schema:
    type: string
- description: The deployment name
  example: '"example string"'
  in: path
  name: agent_deployment_name
  required: true
  schema:
    type: string
requestBody:
  content:
    application/json:
      schema:
        $ref: ./definitions.yml#/apiCreateAgentDeploymentReleaseInputPublic
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: ./definitions.yml#/apiCreateAgentDeploymentReleaseOutput
    description: A successful response.
    headers:
      ratelimit-limit:
        $ref: ../../shared/headers.yml#/ratelimit-limit
      ratelimit-remaining:
        $ref: ../../shared/headers.yml#/ratelimit-remaining
      ratelimit-reset:
        $ref: ../../shared/headers.yml#/ratelimit-reset
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "404":
    $ref: ../../shared/responses/not_found.yml
  "429":
    $ref: ../../shared/responses/too_many_requests.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
security:
- bearer_auth:
  - genai:create
summary: Create a Agent Workspace Deployment Release
tags:
- GradientAI Platform
x-codeSamples:
- $ref: examples/curl/genai_create_agent_workspace_deployment_release.yml
