description: To list all agent workspace deployment releases, send a GET request to
  `/v2/gen-ai/agent-workspace-deployments/{agent_deployment_uuid}/releases`.
operationId: genai_list_agent_workspace_deployment_releases
parameters:
- description: The id of the deployment
  example: '"123e4567-e89b-12d3-a456-426614174000"'
  in: path
  name: agent_deployment_uuid
  required: true
  schema:
    type: string
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: ./definitions.yml#/apiListAgentDeploymentReleasesOutput
    description: A successful response.
    headers:
      ratelimit-limit:
        $ref: ../../shared/headers.yml#/ratelimit-limit
      ratelimit-remaining:
        $ref: ../../shared/headers.yml#/ratelimit-remaining
      ratelimit-reset:
        $ref: ../../shared/headers.yml#/ratelimit-reset
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "404":
    $ref: ../../shared/responses/not_found.yml
  "429":
    $ref: ../../shared/responses/too_many_requests.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
security:
- bearer_auth:
  - genai:read
summary: List Agent Workspace Deployment Releases
tags:
- GradientAI Platform
x-codeSamples:
- $ref: examples/curl/genai_list_agent_workspace_deployment_releases.yml
