description: To delete an agent workspace deployment, send a DELETE request to `/v2/gen-ai/agent-workspaces/{agent_workspace_name}/agent-deployments/{agent_deployment_name}`.
operationId: genai_delete_agent_workspace_deployment
parameters:
- description: Unique agent workspace name
  example: '"example string"'
  in: path
  name: agent_workspace_name
  required: true
  schema:
    type: string
- description: The name of the deployment
  example: '"example string"'
  in: path
  name: agent_deployment_name
  required: true
  schema:
    type: string
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: ./definitions.yml#/apiDeleteAgentWorkspaceDeploymentOutput
    description: A successful response.
    headers:
      ratelimit-limit:
        $ref: ../../shared/headers.yml#/ratelimit-limit
      ratelimit-remaining:
        $ref: ../../shared/headers.yml#/ratelimit-remaining
      ratelimit-reset:
        $ref: ../../shared/headers.yml#/ratelimit-reset
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "404":
    $ref: ../../shared/responses/not_found.yml
  "429":
    $ref: ../../shared/responses/too_many_requests.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
security:
- bearer_auth:
  - genai:delete
summary: Delete an Agent Workspace Deployment
tags:
- GradientAI Platform
x-codeSamples:
- $ref: examples/curl/genai_delete_agent_workspace_deployment.yml
