type: object
oneOf:
  - required: [prefix]
  - required: [exact]
properties:
  path:
    $ref: app_ingress_spec_rule_string_match_prefix.yml
  authority:
    $ref: app_ingress_spec_rule_string_match_exact.yml
description: The match configuration for the rule.
