properties:
  app_id:
    title: The app ID
    type: string
    example: 4f6c71e2-1e90-4762-9fee-6cc4a0a9f2cf
  force_build:
    format: boolean
    title: Indicates whether to force a build of app from source even if an existing
      cached build is suitable for re-use
    type: boolean
    example: true
required:
- app_id
type: object
