lang: cURL
source: |-
  curl -X PUT \
    -H "Content-Type: application/json"  \
    -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
    "https://api.digitalocean.com/v2/gen-ai/agent-workspaces/adk/agent-deployments/main" \
    -d '{
      "log_insights_enabled": true
    }'
