operationId: delete_kubernetes_cluster

summary: Delete a Kubernetes Cluster

description: |
  To delete a Kubernetes cluster and all services deployed to it, send a DELETE
  request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID`.

  A 204 status code with no body will be returned in response to a successful
  request.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/KubernetesClusterId'

responses:
  '204':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'
