name: Spec Main
# This workflow uploads the latest spec to the team spaces.

on:
  push:
    branches:
      - main
    paths:
      - 'specification/**'
      - 'spectral/**'

jobs:

  lint:
    name: Validate style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: make lint

  generate-main-preview:
    name: Generate Main Preview
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Bundle
        run: make bundle

      - uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: tests/openapi-bundled.yaml

      - name: Upload Main spec
        run: >-
          aws s3 cp tests/openapi-bundled.yaml 
          s3://$SPACES_PATH/DigitalOcean-public.v2.yaml
          --endpoint=$SPACES_ENDPOINT
          --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_SECRET }}
          AWS_DEFAULT_OUTPUT: json
          SPACES_PATH: ${{ secrets.SPACES_PATH }}
          SPACES_ENDPOINT: https://nyc3.digitaloceanspaces.com