name: Spec Main
# This workflow uploads the latest spec to the team spaces.

on:
  push:
    branches:
      - main
    paths:
      - 'specification/**'
      - 'spectral/**'
  workflow_dispatch:

jobs:
  lint:
    name: Validate style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: make lint

  generate-main-preview:
    name: Generate Main Preview
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Bundle
        run: make bundle

      - uses: actions/upload-artifact@v4
        with:
          name: openapi-bundled
          path: tests/openapi-bundled.yaml

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Upload Main spec
        run: >-
          aws s3 cp tests/openapi-bundled.yaml
          ${{ env.SPACES_PATH }}/DigitalOcean-public.v2.yaml
          --endpoint=${{ env.SPACES_ENDPOINT }}
          --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_SECRET }}
          AWS_DEFAULT_OUTPUT: json
          SPACES_PATH: ${{ secrets.SPACES_PATH }}
          SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }}
          AWS_EC2_METADATA_DISABLED: true

      - name: Upload revision spec
        # this uploads a duplicate of the bundled spec with the short sha
        # appended to the file name for reference during client generation.
        run: >-
          aws s3 cp tests/openapi-bundled.yaml
          ${{ secrets.SPACES_PATH }}/DigitalOcean-public-${{ steps.vars.outputs.sha_short }}.v2.yaml
          --endpoint=${{ secrets.SPACES_ENDPOINT }}
          --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_SECRET }}
          AWS_DEFAULT_OUTPUT: json
          SPACES_PATH: ${{ secrets.SPACES_PATH }}
          SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }}
          AWS_EC2_METADATA_DISABLED: true
